### ISSUE TITLE
fr package?

### ISSUE THREAD

**Issue by Loir** [poqudrof/PapAR#2]
Hi, I try to run the PCConfiguration sketch, but I get the error, "The package "fr" does not exist.  You might be missing a library.  I would appreciate any help.  Thanks.

**Comment by Loir** [comment]
I can see that the fr files are in Processing/Libraries/PapAR/src/fr and that there is no jar file in there, but I don't know what I did wrong installing the  library or how to fix it.

**Comment by poqudrof** [comment]
Hello, 

Did you install all the dependencies ? 

https://github.com/poqudrof/PapAR/releases 

Is it the whole error, if not could you paste it here ?

**Comment by Loir** [comment]
Thanks for responding.  Maybe I havne't installed the dependencies correctly, because I do not see the examples for PapAR when I go to File > Examples.  I haven't used Processing for a couple of years, but I have Examples from older sketches.  

Here are the error messages I get when I try to run PcConfiguration.pde   

![screen shot 2016-04-26 at 8 46 11 am](https://cloud.githubusercontent.com/assets/3899693/14818476/6ab6fd26-0b8b-11e6-9320-c29150a3e1d8.png)

I put the whole unzipped folder structure in the libraries folder of my sketchbook. I see the PapAR.jar but no other jar files.  

Here are the error messages I get when I try to run PaperApp2D:

![screen shot 2016-04-26 at 8 44 25 am](https://cloud.githubusercontent.com/assets/3899693/14818508/9ad86620-0b8b-11e6-8c83-055c0d9ccb0e.png)

Thank you for your help.  I am eager to try out your awesome-looking code!

**Comment by Loir** [comment]
To clarify: I do see the jar files for the other folders (reflections, skalato, etc), in the library folder in their folder structure.  But the fr folder is in the src folder for PapAR

Thanks again,

Loir

**Comment by poqudrof** [comment]
I tried on my MacBook there is some fix to do in PCConfiguration, but it is font related, not really with the dependencies. 

I just extracted moved the content of the "libraries" folder from the [Papar Complete](https://github.com/poqudrof/PapAR/releases). Then moved it to Documents / Processing / libraries . 

Once it is done, restart Processing. Then in Processing go to Files ... Examples ... In the pop-up you should see Contributed Libraries with  Papar, skatolo and Toxiclibscore. 

If it is not from the install, it can be from the Processing version. Did you use  3.0.2 ?

**Comment by Loir** [comment]
I followed your directions above in 3.0.2, but I still do not see the libraries under File> Examples.  I was curious and opened 2.1.1, and there are all the contributed libraries.  The Preferences show that the sketchbook folder is the same for both versions.  Does PapAR work with 3.0.2? 

Thanks.

**Comment by poqudrof** [comment]
It is made for 3.0 but if you have the two installs, you may also have two different Processing folder for Sketches and libraries. 

Processing 2.0 sketches might break with Processing 3.0. So when you first start Processing 3.0 it asks you if it needs to create a new sketchbook folder, or something like this. 

 Look into your Documents folder, there might be a Processing and Processing3.0  folder. You should put the libraries in Processing3.0.
