### ISSUE TITLE
Using Cube QR Code

### ISSUE THREAD

**Issue by enric1994** [poqudrof/PapAR#6]
Hi!
Can this library detect QR codes like cubes or others 3D forms?
I would like to use something like that: http://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_multi

pd: The quick start guide works perfect for me! (ubuntu 16.04) :D 

Thanks

**Comment by poqudrof** [comment]
Hello, 

I am glad that the guide worked ! 
The open source projet is now named [PapARt](https://github.com/poqudrof/PapARt), and I encourage you to switch to PapARt. It is much more complete. 

It is possible to make a 3D cube using a cfg configuration. I think if you follow the guide you mentionned you could do it. 

If you want to share it, we could make an example out of it in [papart-examples](https://github.com/poqudrof/Papart-examples). You can file your request there, and I will post an example with  ARToolkitPlus configuration example. 

Thanks.

**Comment by poqudrof** [comment]
I did a proto-application there: 

https://github.com/poqudrof/Papart-examples/tree/master/papart-examples/Camera/Cube 

You just need to fill the  `cube.cfg` file with the correct coordinates. 

https://github.com/poqudrof/Papart-examples/blob/master/papart-examples/Camera/Cube/markers/cube.cfg

I put the svg file describing the current markerboard.

**Comment by enric1994** [comment]
Nice!
It would be nice to have a working Processing example of that cube.
Thank you @poqudrof

**Comment by poqudrof** [comment]
I gave it a try, and some code work, some other don't I'm not sure why. You can try it !
